melons = [
    {
        "name": 'Honeydew',
        "price": 0.99,
        "seedlessness": True,
        "flesh_color": None,
        "rind_color": None,
        "average_weight": None,
    },
    {
        "name": 'Crenshaw',
        "price": 2.00,
        "seedlessness": False,
        "flesh_color": None,
        "rind_color": None,
        "average_weight": None,
    },
    {
        "name": 'Crane',
        "price": 2.50,
        "seedlessness": False,
        "flesh_color": None,
        "rind_color": None,
        "average_weight": None,
    },
    {
        "name": 'Casaba',
        "price": 2.50,
        "seedlessness": False,
        "flesh_color": None,
        "rind_color": None,
        "average_weight": None,
    },
    {
        "name": 'Cantaloupe',
        "price": 0.99,
        "seedlessness": False,
        "flesh_color": None,
        "rind_color": None,
        "average_weight": None,
    },
]